language: node_js
node_js:
        - "node"

cache: yarn

services: 
        - docker

stages:
        - name: run test
          if: type = pull_request
        
        - name: docker build to docker hub
          if: type = push
        
jobs:
        include:
                - stage: run test
                  script: 
                        - yarn test
                
                - stage: docker build to docker hub
                  script:
                        - ./scripts/publish_docker_image.sh

deploy:
        provider: elasticbeanstalk
        region: us-east-1
        app: hilbert-backend
        env: HilbertBackend-env
        bucket_name: elasticbeanstalk-us-east-1-410645838764
        bucket_path: server-hilbert
        on:
                branch: dev
                condition: push 
                #repo: hilbert-hostel/backend
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        session_token: $AWS_SESSION_TOKEN
        
